package main

import (
	"net/http"

	"github.com/Hadhel.ReferenceShop/category"
	"github.com/Hadhel.ReferenceShop/product"
	"github.com/Hadhel.ReferenceShop/user"
)

// Route defines a route
type Route struct {
	Name    string
	Timeout bool
	Method  string
	Pattern string
	Queries []string
	Auth    bool
	Handler func(http.ResponseWriter, *http.Request) (int, string, error)
}

// BaseAPI default base Api
const BaseAPI = "/api/v1"

// Routes is the set of routes handled by the router
type Routes []Route

var routes = Routes{
	Route{
		"GetCategories",
		false,
		"GET",
		BaseAPI + "/categories",
		nil,
		false,
		category.GetCategories,
	},
	Route{
		"AddCategory",
		false,
		"POST",
		BaseAPI + "/categories/add",
		nil,
		false,
		category.AddCategory,
	},
	Route{
		"GetCategoryById",
		false,
		"GET",
		BaseAPI + "/categories/show/{categoryId}",
		nil,
		false,
		category.GetCayegoryByID,
	},
	Route{
		"UpdateCategory",
		false,
		"PUT",
		BaseAPI + "/categories/update",
		nil,
		false,
		category.UpdateCategory,
	},
	Route{
		"DeleteCategory",
		false,
		"DELETE",
		BaseAPI + "/categories/delete/{categoryId}",
		nil,
		false,
		category.DeleteCategoryByID,
	},
	Route{
		"GetAllUsers",
		false,
		"GET",
		BaseAPI + "/users",
		nil,
		false,
		user.GetUsers,
	},
	Route{
		"CreateUser",
		false,
		"POST",
		BaseAPI + "/users/add",
		nil,
		false,
		user.CreateUser,
	},
	Route{
		"GetUser",
		false,
		"GET",
		BaseAPI + "/users/show/{userid}",
		nil,
		false,
		user.GetUser,
	},
	Route{
		"GetUserByEmailAndPwd",
		false,
		"POST",
		BaseAPI + "/users/getUserByEmailAndPwd",
		nil,
		false,
		user.GetUserByEmailAndPwd,
	},
	Route{
		"UpdateUser",
		false,
		"GET",
		BaseAPI + "/users/update",
		nil,
		false,
		user.UpdateUser,
	},
	Route{
		"DeleteUser",
		false,
		"GET",
		BaseAPI + "/users/delete/{userid}",
		nil,
		false,
		user.DeleteUser,
	},
	Route{
		"GetProducts",
		false,
		"GET",
		BaseAPI + "/products",
		nil,
		false,
		product.GetProducts,
	},
	Route{
		"AddProduct",
		false,
		"POST",
		BaseAPI + "/products/add",
		nil,
		false,
		product.AddProduct,
	},
	Route{
		"GetProductById",
		false,
		"GET",
		BaseAPI + "/products/show/{productid}",
		nil,
		false,
		product.GetProductByID,
	},
	Route{
		"UpdateProduct",
		false,
		"PUT",
		BaseAPI + "/products/update",
		nil,
		false,
		product.UpdateProduct,
	},
	Route{
		"DeleteProducts",
		false,
		"DELETE",
		BaseAPI + "/products/delete/{productid}",
		nil,
		false,
		product.DeleteProductByID,
	}, Route{
		"GetImages",
		false,
		"GET",
		BaseAPI + "/images",
		nil,
		false,
		product.GetProductImages,
	},
	Route{
		"AddImage",
		false,
		"POST",
		BaseAPI + "/images/add",
		nil,
		false,
		product.AddProductImage,
	},
	Route{
		"GetImageById",
		false,
		"GET",
		BaseAPI + "/images/show/{imageid}",
		nil,
		false,
		product.GetProductImageByID,
	},
	Route{
		"UpdateImage",
		false,
		"PUT",
		BaseAPI + "/images/update",
		nil,
		false,
		product.UpdateProductImage,
	},
	Route{
		"DeleteImages",
		false,
		"DELETE",
		BaseAPI + "/images/delete/{imageid}",
		nil,
		false,
		product.DeleteProductImageByID,
	},
	Route{
		"GetProductVariantes",
		false,
		"GET",
		BaseAPI + "/variantes",
		nil,
		false,
		product.GetProductVariantes,
	},
	Route{
		"AddProductVariante",
		false,
		"POST",
		BaseAPI + "/variantes/add",
		nil,
		false,
		product.AddProductVariante,
	},
	Route{
		"GetProductVarianteById",
		false,
		"GET",
		BaseAPI + "/variantes/show/{varianteid}",
		nil,
		false,
		product.GetProductVarianteByID,
	},
	Route{
		"UpdateProductVariante",
		false,
		"PUT",
		BaseAPI + "/variantes/update",
		nil,
		false,
		product.UpdateProductVariante,
	},
	Route{
		"DeleteProductVariantes",
		false,
		"DELETE",
		BaseAPI + "/variantes/delete/{varianteid}",
		nil,
		false,
		product.DeleteProductVarianteByID,
	},
	Route{
		"GetProductVarianteValues",
		false,
		"GET",
		BaseAPI + "/varianteValues",
		nil,
		false,
		product.GetProductVarianteValues,
	},
	Route{
		"AddProductVarianteValue",
		false,
		"POST",
		BaseAPI + "/varianteValues/add",
		nil,
		false,
		product.AddProductVarianteValue,
	},
	Route{
		"GetProductVarianteValueById",
		false,
		"GET",
		BaseAPI + "/varianteValues/show/{varianteValueid}",
		nil,
		false,
		product.GetProductVarianteValueByID,
	},
	Route{
		"UpdateProductVarianteValue",
		false,
		"PUT",
		BaseAPI + "/varianteValues/update",
		nil,
		false,
		product.UpdateProductVarianteValue,
	},
	Route{
		"DeleteProductVarianteValues",
		false,
		"DELETE",
		BaseAPI + "/varianteValues/delete/{varianteValueid}",
		nil,
		false,
		product.DeleteProductVarianteValueByID,
	},
	Route{
		"GetProductStocks",
		false,
		"GET",
		BaseAPI + "/stocks",
		nil,
		false,
		product.GetProductStocks,
	},
	Route{
		"AddProductStock",
		false,
		"POST",
		BaseAPI + "/stocks/add",
		nil,
		false,
		product.AddProductStock,
	},
	Route{
		"GetProductStockById",
		false,
		"GET",
		BaseAPI + "/stocks/show/{stockid}",
		nil,
		false,
		product.GetProductStockByID,
	},
	Route{
		"UpdateProductStock",
		false,
		"PUT",
		BaseAPI + "/stocks/update",
		nil,
		false,
		product.UpdateProductStock,
	},
	Route{
		"DeleteProductStocks",
		false,
		"DELETE",
		BaseAPI + "/stocks/delete/{stockid}",
		nil,
		false,
		product.DeleteProductStockByID,
	},
	Route{
		"GetProductPrices",
		false,
		"GET",
		BaseAPI + "/prices",
		nil,
		false,
		product.GetProductPrices,
	},
	Route{
		"AddProductPrice",
		false,
		"POST",
		BaseAPI + "/prices/add",
		nil,
		false,
		product.AddProductPrice,
	},
	Route{
		"GetProductPriceById",
		false,
		"GET",
		BaseAPI + "/prices/show/{priceid}",
		nil,
		false,
		product.GetProductPriceByID,
	},
	Route{
		"UpdateProductPrice",
		false,
		"PUT",
		BaseAPI + "/prices/update",
		nil,
		false,
		product.UpdateProductPrice,
	},
	Route{
		"DeleteProductPrices",
		false,
		"DELETE",
		BaseAPI + "/prices/delete/{priceid}",
		nil,
		false,
		product.DeleteProductPriceByID,
	},
}
